vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /media/properties
            upload_destination: '%kernel.project_dir%/public/media/properties'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        rent_image:
            uri_prefix: /media/rent
            upload_destination: '%kernel.project_dir%/public/media/rent'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        user_image:
            uri_prefix: /media/avatar
            upload_destination: '%kernel.project_dir%/public/media/avatar'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        galerie_image:
            uri_prefix: /media/galerie
            upload_destination: '%kernel.project_dir%/public/media/galerie'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        appartementA_image:
            uri_prefix: /media/appartementA
            upload_destination: '%kernel.project_dir%/public/media/appartementA'
            namer: Vich\UploaderBundle\Naming\UniqidNamer